export enum ERoleType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  TENANT_REVIEWER = 'TENANT_REVIEWER',
  TENANT_EDITOR = 'TENANT_EDITOR',
  INT_SCHOOL = 'INT_SCHOOL',
  INT_TEACHER = 'INT_TEACHER',
  INT_STUDENT = 'INT_STUDENT',
}
